# Generated by Django 3.2.4 on 2021-06-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0004_auto_20210625_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='Venue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='Venue_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
